engines:
  golint:
    enabled: true
    checks:
      GoLint/Comments/DocComments:
        enabled: false
  gofmt:
    enabled: true
  govet:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
    checks:
      box-sizing:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "**.go"
  - "**.js"
  - "**.css"
  - "**.md"
exclude_paths:
- "manual/templates/scripts/**.pack.js"
- "manual/templates/styles/highlight-github.css"
- "manual/templates/styles/markdown.css"
- "**/vendor/"
- "**/build/"
- "**_test.go"
- "testing/**"

