engines:
  golint:
   	enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  markdownlint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "**.go"
  - "**.js"
  - "**.css"
  - "**.md"
exclude_paths:
- "manual/templates/scripts/**.pack.js"
- "manual/templates/styles/highlight-github.css"
- "manual/templates/styles/markdown.css"
- "**/vendor/"
- "**/build/"
