language: go
go:
  - 1.11.x
os:
  - linux
env:
  global:
    - GO111MODULE=on
    - CGO_ENABLED=0
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
script: skip
install: skip

jobs:
  include:
    - stage: test
      name: Run Tests
      script:
        - go run ./build test
    - stage: release
      name: Release
      if: tag =~ ^v\d+\.\d+\.\d+|snapshot-.+$
      script:
        - go run ./build build
      deploy:
        provider: releases
        api_key: "$GITHUB_DEPLOY_TOKEN"
        file_glob: true
        file: var/dist/*
        skip_cleanup: true
        name: $TRAVIS_TAG
        on:
          tags: true
