language: go
go:
  - 1.11.x
install: skip
os:
  - linux
services:
  - docker
env:
  global:
    - GO111MODULE=on
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
script: skip

jobs:
  include:
    - stage: test
      name: Run Tests
      script:
        - go run ./build test
    - stage: release
      name: Release
      if: tag =~ ^v\d+\.\d+\.\d+|snapshot-.+$
      script:
        - go run ./build build
      deploy:
        provider: releases
        api_key: "$GITHUB_DEPLOY_TOKEN"
        file_glob: true
        file: dist/packages/*
        skip_cleanup: true
        name: $TRAVIS_TAG
        on:
          tags: true
